name: Sync Crowdin translations

on:
  push:
    branches:
      - 'main'
    paths:
      - 'app/src/main/res/values/strings.xml'
      - '.github/workflows/crowdin.yml'
  schedule:
    - cron: "0 17 * * 6" # weekly
  workflow_dispatch:

jobs:
  sync-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crowdin
        uses: crowdin/github-action@1.0.4
        with:
          config: crowdin.yml
          upload_translations: true
          download_translations: true
          push_translations: true
          create_pull_request: false
          localization_branch_name: l10n
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: 506998
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
      - name: Commit to main
        run: |
          git checkout main
          git merge l10n
          git push
